In [150]:
df1 = pd.read_pickle('raw/records.pkl')
df2 = pd.read_pickle('raw/samples.pkl')

In [151]:
df1.head()

,Accession,ExtRelations,FTPLink,GDS,GEO2R,GPL,GSE,Id,Item,PDAT,...,entryType,gdsType,n_samples,ptechType,subsetInfo,summary,suppFile,taxon,title,valType
0,GSE122352,[],ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE122nn...,,no,25788,122352,200122352,[],2019/03/12,...,GSE,Expression profiling by RT-PCR,12,,,Paroxysmal Nocturnal Hemoglobinuria (PNH) is a...,TXT,Homo sapiens,Real-time quantitative PCR analysis of human e...,
1,GSE125941,"[{'TargetObject': 'SRP183018', 'RelationType':...",ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE125nn...,,no,22790,125941,200125941,[],2019/03/12,...,GSE,Expression profiling by high throughput sequen...,15,,,Some specific sarcomas and leukemias are defin...,,Homo sapiens,FET fusion oncoprotein-regulated genes in HT10...,
2,GSE113010,"[{'TargetObject': 'SRP139607', 'RelationType':...",ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE113nn...,,no,17303,113010,200113010,[],2019/03/12,...,GSE,Expression profiling by high throughput sequen...,9,,,Rationale - Regulatory T (Treg) cells suppress...,XLSX,Homo sapiens,Defining the transcriptome of T cells transduc...,
3,GSE93040,[],ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE93nnn...,,no,11154,93040,200093040,[],2019/03/12,...,GSE,Genome binding/occupancy profiling by high thr...,28,,,This SuperSeries is composed of the SubSeries ...,BW,Homo sapiens,Release of paused RNA-Polymerase II at specifi...,
4,GSE93039,"[{'TargetObject': 'SRP095865', 'RelationType':...",ftp://ftp.ncbi.nlm.nih.gov/geo/series/GSE93nnn...,,no,11154,93039,200093039,[],2019/03/12,...,GSE,Expression profiling by high throughput sequen...,2,,,Transcriptional activation leads to transient ...,TXT,Homo sapiens,Release of paused RNA-Polymerase II at specifi...,

In [158]:
df1_clean = df1['Id title summary'.split()].rename(columns={'Id':'geo_id', 'title':'Study_Title'})
df1_clean.head()

,geo_id,Study_Title,summary
0,200122352,Real-time quantitative PCR analysis of human e...,Paroxysmal Nocturnal Hemoglobinuria (PNH) is a...
1,200125941,FET fusion oncoprotein-regulated genes in HT10...,Some specific sarcomas and leukemias are defin...
2,200113010,Defining the transcriptome of T cells transduc...,Rationale - Regulatory T (Treg) cells suppress...
3,200093040,Release of paused RNA-Polymerase II at specifi...,This SuperSeries is composed of the SubSeries ...
4,200093039,Release of paused RNA-Polymerase II at specifi...,Transcriptional activation leads to transient ...

In [163]:
df2_clean = df2.drop(columns='accession').rename(columns={'title':'Sample_Title'})
df2_clean.head()

      geo_id  nsamples        date     Sample_Title
0  200000001        38  2001/01/22   NHGRI_UACC-647
1  200000001        38  2001/01/22    NHGRI_M91-054
2  200000001        38  2001/01/22  NHGRI_UACC-1012
3  200000001        38  2001/01/22    NHGRI_TD-1348
4  200000001        38  2001/01/22    NHGRI_WM1791C

In [165]:
df = pd.merge(df1_clean, df2_clean, on='geo_id')
df.head()

,geo_id,Study_Title,summary,nsamples,date,Sample_Title
0,200122352,Real-time quantitative PCR analysis of human e...,Paroxysmal Nocturnal Hemoglobinuria (PNH) is a...,12,2019/03/12,Control 1
1,200122352,Real-time quantitative PCR analysis of human e...,Paroxysmal Nocturnal Hemoglobinuria (PNH) is a...,12,2019/03/12,Patient 1
2,200122352,Real-time quantitative PCR analysis of human e...,Paroxysmal Nocturnal Hemoglobinuria (PNH) is a...,12,2019/03/12,Patient 6
3,200122352,Real-time quantitative PCR analysis of human e...,Paroxysmal Nocturnal Hemoglobinuria (PNH) is a...,12,2019/03/12,Patient 2
4,200122352,Real-time quantitative PCR analysis of human e...,Paroxysmal Nocturnal Hemoglobinuria (PNH) is a...,12,2019/03/12,Control 4

In [171]:
specific_geoid = '200122352'
specific_geoid = '200122354'
sample_titles = list(df[df['geo_id']==specific_geoid].Sample_Title)
print('You have selected: ', specific_geoid)
print('It is titled:', df.loc[specific_geoid])

In [176]:
df[df['geo_id']==specific_geoid]

,geo_id,Study_Title,summary,nsamples,date,Sample_Title
141522,200122354,RNF8 is responsible for ATRA resistance in var...,GTF2I-RARA is a newly identified RARA fusion g...,2,2018/11/10,U937_fusion-seq
141523,200122354,RNF8 is responsible for ATRA resistance in var...,GTF2I-RARA is a newly identified RARA fusion g...,2,2018/11/10,U937_Input-seq